// frontend/cv.tsx
import iconTS from "@/assets/icons/typescript.svg";
import iconJS from "@/assets/icons/javascript.svg";
import iconPython from "@/assets/icons/python.svg";
import iconC from "@/assets/icons/c.svg";
import iconCpp from "@/assets/icons/cpp.svg";
import iconQt from "@/assets/icons/qt.svg";
import iconBash from "@/assets/icons/bash.svg";
import iconReact from "@/assets/icons/react.svg";
import iconVue from "@/assets/icons/vue.svg";
import iconDjango from "@/assets/icons/django.svg";
import iconDocker from "@/assets/icons/docker.svg";
import iconLinux from "@/assets/icons/linux.svg";
import iconGit from "@/assets/icons/git-with-text.svg";
import iconJetBrains from "@/assets/icons/jetbrains.svg";
import iconEmacs from "@/assets/icons/emacs.svg";
import iconNginx from "@/assets/icons/nginx.svg";
import iconEthereum from "@/assets/icons/ethereum.svg";
import iconSolana from "@/assets/icons/solana.svg";
import iconJava from "@/assets/icons/java.svg";
import iconCSharp from "@/assets/icons/csharp.svg";

export interface Skill {
    name: string;
    icon?: string;
    disabled?: boolean;
    group?: SkillGroup;
}

export interface SkillGroup {
    name: string;
    disabled?: boolean;
}

const _skillGroups = {
    programmingLanguages: {
        name: "Programming Languages",
    },
    frameworksAndTechnologies: {
        name: "Frameworks & Technologies",
    },
    otherTools: {
        name: "Other Tools",
    },
    automation: {
        name: "Automation Industry"
    },
    others: {
        name: "Others",
    },
    stale: {
        name: "Stale",
        disabled: true,
    },
}
export const skillGroups = _skillGroups as Record<keyof typeof _skillGroups, SkillGroup>;

const _skills = {
    javascript: {
        name: "JavaScript",
        icon: iconJS,
        group: skillGroups.programmingLanguages,
    },
    typescript: {
        name: "TypeScript",
        icon: iconTS,
        group: skillGroups.programmingLanguages,
    },
    c: {
        name: "C",
        icon: iconC,
        group: skillGroups.programmingLanguages,
    },
    cpp: {
        name: "C++",
        icon: iconCpp,
        group: skillGroups.programmingLanguages,
    },
    python: {
        name: "Python",
        icon: iconPython,
        group: skillGroups.programmingLanguages,
    },
    bash: {
        name: "Bash",
        icon: iconBash,
        group: skillGroups.programmingLanguages,
    },
    qt: {
        name: "Qt",
        icon: iconQt,
        group: skillGroups.frameworksAndTechnologies,
    },
    react: {
        name: "ReactJS",
        icon: iconReact,
        group: skillGroups.frameworksAndTechnologies,
    },
    vue: {
        name: "Vue.js",
        icon: iconVue,
        group: skillGroups.frameworksAndTechnologies,
    },
    django: {
        name: "Django",
        icon: iconDjango,
        group: skillGroups.frameworksAndTechnologies,
    },
    ethereum: {
        name: "Ethereum",
        icon: iconEthereum,
        group: skillGroups.frameworksAndTechnologies,
    },
    solana: {
        name: "Solana",
        icon: iconSolana,
        group: skillGroups.frameworksAndTechnologies,
        disabled: true,
    },
    nginx: {
        name: "Nginx",
        icon: iconNginx,
        group: skillGroups.frameworksAndTechnologies,
    },
    docker: {
        name: "Docker",
        icon: iconDocker,
        group: skillGroups.otherTools,
    },
    git: {
        name: "Git",
        icon: iconGit,
        group: skillGroups.otherTools,
    },
    jetbrains: {
        name: "JetBrains",
        icon: iconJetBrains,
        group: skillGroups.otherTools,
    },
    linux: {
        name: "Linux",
        icon: iconLinux,
        group: skillGroups.otherTools,
    },
    emacs: {
        name: "Emacs",
        icon: iconEmacs,
        group: skillGroups.otherTools,
    },
    plc: {
        name: "PLC programming",
        group: skillGroups.automation,
    },
    tiaPortal: {
        name: "TIA Portal",
        group: skillGroups.automation,
        disabled: true,
    },
    soMachine: {
        name: "SoMachine",
        group: skillGroups.automation,
        disabled: true,
    },
    abbVFD: {
        name: "ABB VFDs (basic)",
        group: skillGroups.automation,
        disabled: true,
    },
    java: {
        name: "Java",
        icon: iconJava,
        group: skillGroups.stale,
    },
    csharp: {
        name: "C#",
        icon: iconCSharp,
        group: skillGroups.stale,
    },
    teaching: {
        name: "Teaching",
        group: skillGroups.others,
        disabled: true,
    },
    technicalWriting: {
        name: "Technical writing",
        group: skillGroups.others,
    },
};

export const skills = _skills as Record<keyof typeof _skills, Skill>;

export interface Group {
    name: string;
    disabled?: boolean;
}

export interface Entry {
    node: () => JSX.Element;
    startDate: string;
    endDate?: string;
    displayDate?: string;
    skills: Array<Skill | string>;
    labels?: string[];
    group?: Group;
}

const _groups = {
    education: {
        name: "Education",
    },
    professionalExperience: {
        name: "Professional Experience"
    },
    otherExperience: {
        name: "Other experience",
    },
    extraCurricular: {
        name: "Extra-curricular",
        disabled: true,
    }
}

export const groups = _groups as Record<keyof typeof _groups, Group>;

const _entries = {
    evoltSoftwareEngineer: {
        node: () => <span><b>Evolt</b>, Software Engineer</span>,
        startDate: "2022-01",
        displayDate: "Jan 2022 - present",
        skills: [skills.javascript, skills.typescript, skills.react, skills.git, skills.docker, skills.ethereum],
        labels: ["Backend", "Frontend", "Blockchain"],
        group: groups.professionalExperience,
    },
    evoltInternship: {
        node: () => <span><b>Evolt</b>, one month internship</span>,
        startDate: "2021-12",
        displayDate: "Dec 2021",
        skills: [skills.python, skills.django, skills.docker],
        labels: ["Backend"],
        group: groups.professionalExperience,
    },
    bachelor: {
        node: () => (
            <span>
                <b>Bachelor of Electrical Engineering</b>, Department of
                Automation and Electronics, Faculty of Electrical
                Engineering, University of Sarajevo
                <br />
                <pre>- GPA 9.19/10.00</pre>
            </span>
        ),
        startDate: "2017",
        endDate: "2020",
        group: groups.education,
    },
    flameshot: {
        node: () => (
            <span>
                <a href="https://flameshot.org" target="_blank">
                    <b>Flameshot</b>
                </a>,
                A Free & Open Source Screenshot Program <br />
            </span>
        ),
        startDate: "2021",
        endDate: "present",
        labels: ["Co-maintainer", "Developer", "Tester", "UI/UX Designer"],
        group: groups.otherExperience,
    },
    rotatingLedDisplay: {
        node: () => (
            <span>
                <a
                    href="https://github.com/veracioux/rotating-led-display"
                    target="_blank"
                >
                    <b>Rotating LED Display</b>
                </a>,
                High School Project Festival, Hadžići, Bosnia and Herzegovina
                <br />
            </span>
        ),
        startDate: "2017",
        displayDate: "Spring 2017",
        skills: [skills.cpp],
        labels: ["Lead Engineer", "Lead Designer", "Lead Programmer"],
        group: groups.otherExperience,
    },
    woodFall: {
        node: () => (
            <span>
                <a
                    href="https://github.com/veracioux/wood-fall"
                    target="_blank"
                >
                    <b>Wood Fall</b>
                </a>,
                video game, solo project
            </span>
        ),
        startDate: "2016",
        endDate: "2017",
        // skills: ["C#", "Unity"],
        labels: ["Programmer", "Artist", "Sound Designer", "Publisher"],
        group: groups.otherExperience,
    },
    renovation: {
        node: () => <span><b>Renovation of sports grounds</b>, Kamberovića polje Zenica</span>,
        startDate: "2016-03",
        endDate: "2016-11",
        displayDate: "Mar - Nov 2016",
        labels: ["Participant", "Youth Leadership Program 2016"],
        group: groups.extraCurricular,
    },
    demosPMS: {
        node: () => (
            <span>
                <b>Undergraduate Teaching Assistant</b>,
                Faculty of Electrical Engineering,
                University of Sarajevo,
                Course: <i>Design of Microprocessor Systems</i>
            </span>
        ),
        startDate: "2021-03",
        endDate: "2021-06",
        displayDate: "Mar - Jun 2021",
        skills: [skills.plc, skills.soMachine, skills.teaching],
        labels: ["PLC programming", "SoMachine"],
        group: groups.professionalExperience,
    },
    elektromatik: {
        node: () => (
            <span>
                Internship, <a
                href="https://search.bisnode.ba/ba/367191/elektromatik-d-o-o-zenica/"
                target="_blank"
            >
                    Elektromatik d.o.o. Zenica
                </a>
            </span>
        ),
        startDate: "2019",
        endDate: "2020",
        displayDate: "Summer 2019, Summer 2020",
        skills: [skills.plc, skills.tiaPortal, skills.abbVFD],
        labels: ["PLC programming", "Industrial sensors", "Motor control", "Industrial schematic design"],
        group: groups.professionalExperience,
    },
    demosTP: {
        node: () => (
            <span>
                <b>Undergraduate Teaching Assistant</b>,
                Faculty of Electrical Engineering,
                University of Sarajevo,
                Course: <i>Programming Techniques</i>
            </span>
        ),
        startDate: "2019-03",
        endDate: "2019-06",
        displayDate: "Mar - Jun 2019",
        skills: [skills.cpp, skills.teaching],
        labels: ["C++"],
        group: groups.professionalExperience,
    },
    stackExchange: {
        node: () => (
            <span>
                <b>Answering community questions</b>, <a
                href="https://math.stackexchange.com/users/450231"
                target="_blank"
            >
                    Mathematics StackExchange
                </a>
            </span>
        ),
        startDate: "2018",
        endDate: "present",
        skills: [skills.teaching],
        group: groups.extraCurricular,
    },
    githubProjects: {
        node: () => (
            <span>
                <b>
                    Various personal projects on <a
                    href="https://github.com/veracioux"
                    target="_blank"
                >
                        GitHub
                    </a>
                </b>
            </span>
        ),
        startDate: "2018",
        endDate: "present",
        group: groups.otherExperience,
    },
}

export const entries = _entries as Record<keyof typeof _entries, Entry>;

// frontend/src/components/sections/CV.vue
<script setup lang="ts">
import TimelineEntry from "@/components/cv/TimelineEntry.vue";
import Label from "@/components/generic/Label.vue";
import {onMounted, ref} from "vue";
import SkillsPane from "@/components/cv/SkillsPane.vue";
import LanguagesPane from "@/components/cv/LanguagesPane.vue";
import SectionTitle from "@/components/SectionTitle.vue";

const root = ref<HTMLElement>();

onMounted(() => {
    // Set target="_blank" on all anchor tags
    const anchors = root.value?.getElementsByTagName("a");
    if (!anchors) return;
    for (let i = 0; i < anchors.length; ++i) {
        const item = anchors.item(i)!;
        item.setAttribute("target", "_blank");
    }
});
</script>

<template>
    <div ref="root" class="section">
        <SectionTitle :class="s.sectionTitle"> Curriculum Vitae </SectionTitle>
        <div class="content">
            <table class="timeline">
                <TimelineEntry
                    start-date="2022-01"
                    display-date="Jan 2022 - present"
                    first
                >
                    <b>Evolt</b>, Software Engineer
                    <div class="labelContainer">
                        <Label title="Backend" />
                        <Label title="Frontend" />
                        <Label title="Blockchain" />
                    </div>
                </TimelineEntry>
                <TimelineEntry start-date="2021-12" display-date="Dec 2021">
                    <b>Evolt</b>, one month internship
                    <div class="labelContainer">
                        <Label title="Backend" />
                    </div>
                </TimelineEntry>
                <TimelineEntry start-date="2017" end-date="2020">
                    <b>Bachelor of Electrical Engineering</b>, Department of
                    Automation and Electronics, Faculty of Electrical
                    Engineering, University of Sarajevo
                    <br />
                    <pre>- GPA 9.19/10.00</pre>
                </TimelineEntry>
                <TimelineEntry start-date="2021" end-date="present">
                    <a href="https://flameshot.org" target="_blank">
                        <b>Flameshot</b> </a
                    >, A Free & Open Source Screenshot Program <br />
                    <div class="labelContainer">
                        <Label title="Co-maintainer" />
                        <Label title="Developer" />
                        <Label title="Tester" />
                        <Label title="UI/UX Designer" />
                    </div>
                </TimelineEntry>
                <TimelineEntry start-date="2017" display-date="Spring 2017">
                    <a
                        href="https://github.com/veracioux/rotating-led-display"
                        target="_blank"
                    >
                        <b>Rotating LED Display</b> </a
                    >, High School Project Festival, Hadžići, Bosnia and
                    Herzegovina
                    <br />
                    <div class="labelContainer">
                        <Label title="Lead Engineer" />
                        <Label title="Lead Designer" />
                        <Label title="Lead Programmer" />
                    </div>
                </TimelineEntry>
                <TimelineEntry start-date="2016" end-date="2017">
                    <a
                        href="https://github.com/veracioux/wood-fall"
                        target="_blank"
                    >
                        <b>Wood Fall</b> </a
                    >, video game, solo project
                    <br />
                    <div class="labelContainer">
                        <Label title="Programmer" />
                        <Label title="Artist" />
                        <Label title="Sound Designer" />
                        <Label title="Publisher" />
                    </div>
                </TimelineEntry>
                <TimelineEntry
                    start-date="2016-03"
                    end-date="2016-11"
                    display-date="Mar - Nov 2016"
                >
                    <b>Renovation of sports grounds</b>, Kamberovića polje
                    Zenica
                    <div class="labelContainer">
                        <Label title="Participant" />
                        <Label title="Youth Leadership Program 2016" />
                    </div>
                </TimelineEntry>
                <TimelineEntry
                    start-date="2021-03"
                    end-date="2021-06"
                    display-date="Mar - Jun 2021"
                >
                    <b>Undergraduate Teaching Assistant</b>, Faculty of
                    Electrical Engineering, University of Sarajevo, Course:
                    <i>Design of Microprocessor Systems</i>
                    <div class="labelContainer">
                        <Label title="PLC programming" />
                        <Label title="SoMachine" />
                    </div>
                </TimelineEntry>
                <TimelineEntry
                    start-date="2019"
                    end-date="2020"
                    display-date="Summer 2019, Summer 2020"
                >
                    Internship,
                    <a
                        href="https://search.bisnode.ba/ba/367191/elektromatik-d-o-o-zenica/"
                        target="_blank"
                    >
                        Elektromatik d.o.o. Zenica
                    </a>
                    <br />
                    <div class="labelContainer">
                        <Label title="PLC programming" />
                        <Label title="Industrial sensors" />
                        <Label title="Motor control" />
                        <Label title="Industrial schematic design" />
                    </div>
                </TimelineEntry>
                <TimelineEntry
                    start-date="2019-03"
                    end-date="2019-06"
                    display-date="Mar - Jun 2019"
                >
                    <b>Undergraduate Teaching Assistant</b>, Faculty of
                    Electrical Engineering, University of Sarajevo, Course:
                    <i>Programming Techniques</i>
                    <div class="labelContainer">
                        <Label title="C++" />
                    </div>
                </TimelineEntry>
                <TimelineEntry start-date="2018" end-date="present">
                    <b>Answering community questions</b>,
                    <a
                        href="https://math.stackexchange.com/users/450231"
                        target="_blank"
                    >
                        Mathematics StackExchange
                    </a>
                </TimelineEntry>
                <TimelineEntry start-date="2018" end-date="present" last>
                    <b>
                        Various personal projects on
                        <a href="https://github.com/veracioux">GitHub</a>
                    </b>
                    <br />
                </TimelineEntry>
            </table>
            <aside class="sidePane">
                <SkillsPane class="skillsPane" />
                <LanguagesPane class="languagesPane" />
            </aside>
        </div>
        <div class="overlayContainer">
            <div class="overlay top" />
            <div class="overlay bottom" />
        </div>
    </div>
</template>

<style scoped lang="scss">
@use "@/assets/common.module.scss" as common;
@import "@/assets/global.scss";
@import "@/assets/home.scss";

$colorDimText: rgba(var(--color-text-rgb), 0.7);

.section {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    color: $colorDimText;
    background: var(--color-background-2);
    width: 100vw;
    padding-bottom: 160px;

    .content {
        display: flex;
        flex-direction: column;
        justify-content: start;
        gap: 48px;
        padding-top: 64px;

        @include screenWidthAbove($xlarge) {
            flex-direction: row;
            gap: 16px;
        }

        .timeline {
            border-spacing: 16px 0;
            line-height: 200%;
            max-width: 900px;

            :global(td) {
                padding: 0;
            }
        }

        .sidePane {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: inherit;

            @include screenWidthAbove($xlarge) {
                gap: 32px;
                position: sticky;
                top: 130px;
                bottom: 150px;
                height: 100%;
                align-items: start;
            }

            :deep(.subsectionTitle) {
                text-align: left;
                color: var(--color-text);
            }

            :deep(.subsubsectionTitle) {
                text-align: left;
                margin: 0 12px;
            }
        }
    }

    .overlayContainer {
        @include common.fillParent;
        z-index: 1;
        pointer-events: none;

        display: flex;
        flex-direction: column;
        justify-content: space-between;

        .overlay {
            position: sticky;
            width: 100%;
            pointer-events: auto;

            &.top {
                top: 0;
                height: 160px;
                background: linear-gradient(
                    var(--color-background-2) 60%,
                    #00000000
                );
            }

            &.bottom {
                bottom: 0;
                height: 200px;
                background: linear-gradient(
                    #00000000,
                    var(--color-background-2) 40%
                );
                // On mobile browsers we need to stretch this element downwards because
                // the element may not perfectly hug the bottom of the viewport while
                // scrolling, leaving parts of the underlying text visible.
                &::after {
                    display: block;
                    content: "";
                    transform: translate(0, 170px);
                    height: 100px;
                    width: 100%;
                    background: var(--color-background-2);
                }
            }
        }
    }

    :deep(.titleText) {
        color: var(--color-text);
        z-index: 2;
    }

    :deep(.titleDecoration) {
        fill: var(--color-background-1);
    }
}

.labelContainer {
    @include common.labelContainer;
    justify-content: start;
}
</style>

<style module="s" lang="scss">
.sectionTitle {
    position: sticky;
    top: 0;
    width: 100%;
    z-index: 2;
}
</style>
